name: omnia
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.5+1-beta

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_nav_bar: ^5.0.6
  dots_indicator: ^3.0.0

  cupertino_icons: ^1.0.2
  slide_countdown: ^1.5.0
  url_launcher: ^6.2.3
  flutter_inappwebview: ^5.8.0
  webview_flutter: ^4.4.4
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  image_picker: ^1.0.7
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.17.5
  elegant_notification: ^2.2.2
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  crop_your_image: ^1.1.0
  flutter_svg: ^2.0.10+1
  rive: ^0.13.4


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  
  
  
  
  
  





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/
    - assets/webdev/
    - assets/aiml/
    - assets//fintech/
    - assets/insideout/
    - assets/cp/
    - assets/appdev/
    - assets/blockchain/
    - assets/ama/
    - assets/techoween/
    - assets/qrisosity/
    - assets/sih/
    - assets/RiveAssets/
    - assets/icons/
 
    

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
